spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  server:
    port: ${SERVER_PORT:8080}
  application:
    name: my-note
  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 10240KB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:root123}
      port: ${REDIS_PORT:6379}
my-note:
  time-zone: ${TIME_ZONE:Asia/Ho_Chi_Minh} # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  upload-dir: ${UPLOAD_DIR:D:\workspaces\self_git\loveit-1990\k8s-my-note\assets\uploads\}
  users:
    -
      username: test1
      password: guest1234
      roles: USER
    -
      username: test2
      password: guest1234
      roles: USER
    -
      username: admin
      password: admin1234
      roles: USER,ADMIN