spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USER:dummy}
      password: ${MONGO_PASSWORD:dummy45A2}
      database: ${MONGO_DATA_BASE:my_note}
minio:
  host: ${MINIO_HOST:localhost}
  port: ${MINIO_PORT:9000}
  bucket: ${MINIO_BUCKET:upload-storage}
  secret-key: ${MINIO_SECRET_KEY:dummy}
  access-key: ${MINIO_ACCESS_KEY:dummy123}
  reconnect-enabled: ${MINIO_RECONNECT_ENABLED:true}
  use-ssl: ${MINIO_USE_SSL:false}