apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MONGODB_USERNAME: ZHVtbXk= #dummy
  MONGODB_PASSWORD: ZHVtbXkzNkJh #dummy36Ba
  MONGODB_ROOT_USER: cm9vdA== #root
  MONGODB_ROOT_PASSWORD: YWRtaW4xQjI1 #admin1B25